site_name: Root docs
repo_url: https://github.com/polarpoint-io/python-mkdocs-to-confluence
edit_uri: edit/main/docs

nav:
  - Home: index.md
  - Local development: local-development.md
  - Runbook: runbook.md

docs_dir: docs
plugins:
  - techdocs-core
  - kroki