name: Python CI

permissions:
  id-token: write
  contents: write
  pull-requests: write
  actions: read
  security-events: write

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    types: [ opened, synchronize, reopened ]
  push:
    branches:
      - 'main'

jobs:
  ci:
    uses: NewDay-Data/shared-github-actions/.github/workflows/python-ci.yaml@v2
    with:
      source_dir: 'src'
      tests_dir: 'tests'
  cd:
    needs: ci 
    uses: NewDay-Data/shared-github-actions/.github/workflows/python-cd.yaml@CPE-0000
    with:
      artifact_name: mkdocs_confluence_plugin
      repository_name: nexus_pypi
      extra_plugins: semantic-release-pypi